"""通用缺陷与代码质量模式。"""

from __future__ import annotations

from deepopen.models import Category, Severity
from deepopen.patterns.base import PatternRule, compile_re as _re

PY = frozenset({".py", ".pyw"})
JS = frozenset({".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"})

BUG_RULES: tuple[PatternRule, ...] = (
    PatternRule(
        rule_id="BUG001",
        title="裸 except 吞掉异常",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"^\s*except\s*:"),
        message="except: 会捕获包括 KeyboardInterrupt 在内的所有异常。",
        remediation="改成 except Exception，并记录日志或向上抛出。",
        cwe="CWE-390",
        suffixes=PY,
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG002",
        title="可变默认参数",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"def\s+\w+\s*\([^)]*=\s*(?:\[\]|\{\}|set\(\))"),
        message="函数默认的 list/dict 会在多次调用间共享。",
        remediation="默认值写成 None，在函数体内再创建新容器。",
        suffixes=PY,
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG003",
        title="用 == 比较 None",
        severity=Severity.LOW,
        category=Category.QUALITY,
        pattern=_re(r"(?:==\s*None|None\s*==)"),
        message="对 None 使用 == 在重载了相等运算的对象上可能得到意外结果。",
        remediation="写成 is None / is not None。",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="BUG004",
        title="空 except 主体 pass",
        severity=Severity.LOW,
        category=Category.BUG,
        pattern=_re(r"except[^\n]*:\s*\n\s*pass\b"),
        message="捕获异常后直接 pass，排障时没有信号。",
        remediation="至少记录异常；如果确实可忽略，写明原因注释。",
        suffixes=PY,
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG005",
        title="用 == 比较 True/False",
        severity=Severity.LOW,
        category=Category.QUALITY,
        pattern=_re(r"==\s*(?:True|False)|(?:True|False)\s*=="),
        message="布尔比较通常可以直接使用真值测试。",
        remediation="写成 if flag: / if not flag:。",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="BUG006",
        title="空 catch 块",
        severity=Severity.LOW,
        category=Category.BUG,
        pattern=_re(r"catch\s*\([^)]*\)\s*\{\s*\}"),
        message="空 catch 会吞掉故障。",
        remediation="记录异常或向上抛出。",
        cwe="CWE-390",
        suffixes=frozenset({".java", ".js", ".jsx", ".ts", ".tsx", ".cs", ".php"}),
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG007",
        title="TODO / FIXME 遗留",
        severity=Severity.INFO,
        category=Category.QUALITY,
        pattern=_re(r"(?:^\s*#.*|^\s*//.*)\b(?:TODO|FIXME|XXX|HACK)\b"),
        message="源码中留有待办标记，可能表示未完成的校验或修复。",
        remediation="在合并前处理或转为跟踪工单，不要把安全相关 TODO 带进生产。",
        suffixes=PY | JS | frozenset({".java", ".go", ".php", ".rb", ".cs"}),
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG008",
        title="通配符 import *",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"^\s*from\s+\S+\s+import\s+\*"),
        message="import * 会污染命名空间，可能静默覆盖已有名字。",
        remediation="显式导入需要的符号。",
        suffixes=PY,
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG009",
        title="调试断点留在代码里",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"\bbreakpoint\s*\(|\bpdb\.set_trace\s*\("),
        message="breakpoint / pdb 会在运行时停下进程。",
        remediation="提交前删除，或放到仅本地启用的调试开关后面。",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="BUG010",
        title="raise e 丢失堆栈",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"except[^\n]*as\s+(\w+)\s*:\s*(?:\n\s*)+raise\s+\1\b"),
        message="raise e 会丢掉原始堆栈，排障变难。",
        remediation="写成裸 raise，保留异常链。",
        suffixes=PY,
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG011",
        title="用 type() 做相等判断",
        severity=Severity.LOW,
        category=Category.QUALITY,
        pattern=_re(r"\btype\s*\([^)]+\)\s*(?:==|is)\s*"),
        message="用 type() 再做相等判断无法识别子类。",
        remediation="改用 isinstance(x, T)。",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="BUG012",
        title="JavaScript 使用 == 而不是 ===",
        severity=Severity.LOW,
        category=Category.BUG,
        pattern=_re(r"(?<![!=])==(?!=)"),
        message="== 会做隐式转换，NaN、''、0 很容易比错。",
        remediation="改用 === / !==。",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="BUG013",
        title="使用 var 声明",
        severity=Severity.LOW,
        category=Category.QUALITY,
        pattern=_re(r"(?:^|[\s;{(])var\s+\w+"),
        message="var 会提升到函数作用域，容易造成意外覆盖。",
        remediation="用 const，需要重新赋值时再用 let。",
        suffixes=JS,
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG014",
        title="console.log 遗留",
        severity=Severity.INFO,
        category=Category.QUALITY,
        pattern=_re(r"\bconsole\.(?:log|debug|info)\s*\("),
        message="调试输出可能泄漏内部数据，也会干扰生产日志。",
        remediation="删除或改用受控的前端日志开关。",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="BUG015",
        title="Java printStackTrace",
        severity=Severity.LOW,
        category=Category.BUG,
        pattern=_re(r"\.printStackTrace\s*\("),
        message="只打印堆栈不会进入日志系统，生产环境容易丢记录。",
        remediation="交给日志框架记录，并向上抛出或返回错误。",
        suffixes=frozenset({".java"}),
    ),
    PatternRule(
        rule_id="BUG016",
        title="Java 用 == 比较字符串",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r'"[^"]*"\s*==\s*\w+|\w+\s*==\s*"[^"]*"'),
        message="== 比较的是引用，不是字符内容。",
        remediation="使用 Objects.equals(a, b) 或 a.equals(b)（注意空指针）。",
        suffixes=frozenset({".java"}),
    ),
    PatternRule(
        rule_id="BUG017",
        title="空的 err != nil 分支",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"if\s+err\s*!=\s*nil\s*\{\s*\}"),
        message="发现错误后什么都不做，调用方无法感知失败。",
        remediation="返回 err 或记录后中断当前流程。",
        suffixes=frozenset({".go"}),
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG018",
        title="SELECT *",
        severity=Severity.LOW,
        category=Category.QUALITY,
        pattern=_re(r"\bSELECT\s+\*\s+FROM\b"),
        message="选出全部列会让查询脆弱，表结构一变调用方就可能出错。",
        remediation="显式写出需要的列名。",
        suffixes=PY | frozenset({".sql", ".go", ".java", ".php", ".rb", ".cs"}),
    ),
    PatternRule(
        rule_id="BUG019",
        title="except 后直接 continue",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"except(?:\s+Exception(?:\s+as\s+\w+)?|\s*:)\s*\n\s*continue\b"),
        message="捕获异常后直接进入下一轮，失败被悄悄跳过。",
        remediation="至少记录异常，并确认跳过是业务允许的。",
        suffixes=PY,
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG020",
        title="debugger 语句遗留",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"\bdebugger\s*;"),
        message="debugger 会在开发者工具打开时停下页面。",
        remediation="提交前删除。",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="BUG021",
        title="parseInt 未指定进制",
        severity=Severity.LOW,
        category=Category.BUG,
        pattern=_re(r"\bparseInt\s*\(\s*[^,)]+\s*\)"),
        message="不写进制时，前导 0 在旧引擎里可能被当成八进制。",
        remediation="写成 parseInt(text, 10)。",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="BUG022",
        title="用相等运算比较 NaN",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"(?:===|==|!==|!=)\s*NaN\b|\bNaN\s*(?:===|==|!==|!=)"),
        message="NaN 与任何值（包括自己）做相等比较都是 false。",
        remediation="使用 Number.isNaN(value)。",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="BUG023",
        title="忽略 err 返回值",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"_\s*=\s*err\b"),
        message="把 err 赋给空白标识符等于丢掉失败信号。",
        remediation="检查 err 并返回或中断。",
        suffixes=frozenset({".go"}),
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG024",
        title="Go panic 留在业务路径",
        severity=Severity.INFO,
        category=Category.QUALITY,
        pattern=_re(r"\bpanic\s*\("),
        message="panic 会中断整个 goroutine，不适合表示普通业务错误。",
        remediation="返回 error；只有不可能发生的不变量才用 panic。",
        suffixes=frozenset({".go"}),
    ),
    PatternRule(
        rule_id="BUG025",
        title="Java System.out 调试输出",
        severity=Severity.INFO,
        category=Category.QUALITY,
        pattern=_re(r"System\.out\.print(?:ln)?\s*\("),
        message="标准输出不会进入日志系统，生产环境难以检索。",
        remediation="改用日志框架，并区分级别。",
        suffixes=frozenset({".java"}),
    ),
    PatternRule(
        rule_id="BUG026",
        title="使用 exit/quit",
        severity=Severity.LOW,
        category=Category.QUALITY,
        pattern=_re(r"\b(?:exit|quit)\s*\("),
        message="exit/quit 依赖交互式站点，在模块里调用可能直接结束进程。",
        remediation="库代码抛异常；程序入口用 sys.exit。",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="BUG027",
        title="断言恒假",
        severity=Severity.LOW,
        category=Category.BUG,
        pattern=_re(r"\bassert\s+(?:False|0)\b"),
        message="用 assert 表达“不可达”在 python -O 下会被去掉。",
        remediation="改成 raise RuntimeError，或删除死代码。",
        suffixes=PY,
        skip_comments=False,
    ),
    PatternRule(
        rule_id="BUG028",
        title="与空列表做相等比较",
        severity=Severity.LOW,
        category=Category.QUALITY,
        pattern=_re(r"==\s*\[\s*\]|\[\s*\]\s*=="),
        message="空列表比较既慢，也容易和 None 搞混。",
        remediation="用 if not items: 判断空容器。",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="BUG029",
        title="日志或打印可能含出口令",
        severity=Severity.MEDIUM,
        category=Category.SECRET,
        pattern=_re(
            r"(?:print|logging\.\w+|logger\.\w+|console\.log)\s*\([^)\n]*(?:password|passwd|secret|api[_-]?key|access[_-]?token)"
        ),
        message="把口令或令牌写进日志会扩大泄露面。",
        remediation="日志只保留非敏感标识；密钥不要打印。",
        cwe="CWE-532",
        suffixes=PY | JS,
    ),
    PatternRule(
        rule_id="BUG030",
        title="debugger 语句",
        severity=Severity.LOW,
        category=Category.QUALITY,
        pattern=_re(r"\bdebugger\b"),
        message="debugger 会在有开发者工具时打断执行，不应进入生产包。",
        remediation="删除 debugger，或只在本地构建中启用。",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="BUG031",
        title="空的 for 循环体",
        severity=Severity.LOW,
        category=Category.BUG,
        pattern=_re(r"for\s+\w+\s+in\s+[^:]+:\s*pass\b"),
        message="循环体只有 pass，通常是未写完或无效代码。",
        remediation="补上处理逻辑，或删掉这段循环。",
        suffixes=PY,
        skip_comments=False,
    ),
)
