"""JavaScript / TypeScript / Vue 不安全 DOM 与 Node API。"""

from __future__ import annotations

from deepopen.models import Category, Severity
from deepopen.patterns.base import PatternRule, compile_re as _re

JS = frozenset({".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".vue"})
WEB = JS | frozenset({".html", ".htm"})

JAVASCRIPT_RULES: tuple[PatternRule, ...] = (
    PatternRule(
        rule_id="JS001",
        title="innerHTML / document.write 插入 HTML",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\.(?:innerHTML|outerHTML)\s*=|document\.write\s*\("),
        message="把未转义字符串写入 HTML 可能引入脚本执行。",
        remediation="优先 textContent；必须插入 HTML 时使用维护中的消毒库，并配合 CSP。",
        cwe="CWE-79",
        suffixes=WEB,
    ),
    PatternRule(
        rule_id="JS002",
        title="浏览器或 Node 中的 eval",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\beval\s*\(|new\s+Function\s*\("),
        message="eval / Function 会把字符串当成代码执行。",
        remediation="用 JSON.parse、显式映射表或安全解析器替代。",
        cwe="CWE-95",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="JS003",
        title="dangerouslySetInnerHTML",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"dangerouslySetInnerHTML"),
        message="React 的该 API 会跳过默认转义。",
        remediation="尽量不用；若渲染富文本，先用 HTML sanitizer 并限制允许的标签。",
        cwe="CWE-79",
        suffixes=frozenset({".js", ".jsx", ".ts", ".tsx"}),
    ),
    PatternRule(
        rule_id="JS004",
        title="document.cookie 读写敏感信息",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"document\.cookie"),
        message="脚本可读写 cookie，HttpOnly 才能避免被页面脚本碰到。",
        remediation="会话 cookie 设 HttpOnly、Secure、SameSite；前端不要把令牌放进可被脚本读取的 cookie。",
        cwe="CWE-1004",
        suffixes=WEB,
    ),
    PatternRule(
        rule_id="JS005",
        title="postMessage 目标来源过宽",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"postMessage\s*\([^)]*,\s*['\"]\*['\"]"),
        message="targetOrigin 为 * 时，消息可能被其它窗口接收。",
        remediation="写成明确的源，例如 https://app.example.com。",
        cwe="CWE-346",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="JS006",
        title="Node 用 shell 执行命令",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"""(?:child_process|execa)\.(?:exec|execSync)\s*\(|exec\s*\(\s*['"`][^'"`]*\$\{"""),
        message="exec 会走 shell，字符串拼接会改变命令结构。",
        remediation="改用 execFile/spawn 并传入参数数组，不要拼接命令行。",
        cwe="CWE-78",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="JS007",
        title="localStorage 存放令牌",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"""localStorage\.(?:setItem|set)\s*\(\s*['\"][^'\"]*(token|jwt|session|auth)"""),
        message="localStorage 可被同页脚本读取，不适合放会话令牌。",
        remediation="会话用 HttpOnly cookie；不要把访问令牌长期放在 Web Storage。",
        cwe="CWE-922",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="JS008",
        title="Math.random 用于令牌或会话",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"(?:token|nonce|csrf|session|password|secret)[^\n]{0,40}Math\.random|Math\.random[^\n]{0,40}(?:token|nonce|csrf|session)"),
        message="Math.random 不是密码学安全随机源。",
        remediation="浏览器用 crypto.getRandomValues，Node 用 crypto.randomBytes。",
        cwe="CWE-330",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="JS009",
        title="javascript: URL",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"""['\"]javascript:"""),
        message="javascript: 协议会在导航时执行脚本。",
        remediation="链接只使用 https/http/mailto 等明确协议，并对 URL 做协议白名单。",
        cwe="CWE-79",
        suffixes=WEB,
    ),
    PatternRule(
        rule_id="JS010",
        title="关闭 TLS 校验（Node）",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['\"]?0"),
        message="关闭 Node TLS 校验会导致中间人替换无法被发现。",
        remediation="保持校验；自签场景改为信任指定 CA。",
        cwe="CWE-295",
        suffixes=JS | frozenset({".env", ".yml", ".yaml"}),
        names=frozenset({".env"}),
    ),
)
