"""补充规则：多语言危险 API、密钥形态和配置。"""

from __future__ import annotations

from deepopen.models import Category, Severity
from deepopen.patterns.base import PatternRule, compile_re as _re

PY = frozenset({".py", ".pyw"})
JS = frozenset({".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"})
GO = frozenset({".go"})
JAVA = frozenset({".java", ".kt"})
PHP = frozenset({".php"})
CS = frozenset({".cs"})
RUBY = frozenset({".rb"})
RUST = frozenset({".rs"})
SQL = frozenset({".sql"})
C_FAM = frozenset({".c", ".cc", ".cpp", ".h", ".hpp"})
HTML = frozenset({".html", ".htm"})
YAML = frozenset({".yml", ".yaml"})
TF = frozenset({".tf", ".tfvars"})

MORE_RULES: tuple[PatternRule, ...] = (
    PatternRule(
        rule_id="PY023",
        title="yaml 使用非安全 Loader",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"yaml\.(?:Loader|UnsafeLoader|FullLoader)\b|Loader\s*=\s*yaml\.(?:Loader|UnsafeLoader)"),
        message="FullLoader / UnsafeLoader 可以构造任意对象。",
        remediation="改用 yaml.safe_load。",
        cwe="CWE-502",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY024",
        title="模板关闭自动转义",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"autoescape\s*=\s*False"),
        message="关掉自动转义后，变量会原样进入 HTML。",
        remediation="保持自动转义，只对已经消毒的片段单独标记。",
        cwe="CWE-79",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY026",
        title="numpy 允许 pickle",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"allow_pickle\s*=\s*True"),
        message="allow_pickle 会按 pickle 还原数组文件。",
        remediation="对外文件保持 allow_pickle=False，或改用安全格式。",
        cwe="CWE-502",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY027",
        title="用 input 读取口令",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"(?i)\b(?:password|passwd|secret)\s*=\s*input\s*\("),
        message="input 会回显按键，不适合读口令。",
        remediation="改用 getpass.getpass，或从环境变量读取。",
        cwe="CWE-549",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="JS018",
        title="vm 执行动态代码",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\bvm\.runIn(?:New|This)Context\s*\("),
        message="vm 会把字符串当成脚本执行。",
        remediation="不要把外部字符串交给 vm；用 JSON.parse 或白名单。",
        cwe="CWE-95",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="JS019",
        title="使用已废弃的 createCipher",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\bcrypto\.createCipher\s*\("),
        message="createCipher 使用弱口令派生，且已废弃。",
        remediation="改用 createCipheriv，密钥用随机字节而不是口令字符串。",
        cwe="CWE-327",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="JS020",
        title="按请求地址做跳转",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\.redirect\s*\(\s*req\."),
        message="跳转目标直接来自请求。",
        remediation="只允许站内相对路径。",
        cwe="CWE-601",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="JS021",
        title="使用已废弃的 new Buffer",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"\bnew\s+Buffer\s*\("),
        message="new Buffer(number) 可能带出未初始化内存。",
        remediation="改用 Buffer.from 或 Buffer.alloc。",
        cwe="CWE-120",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="JS022",
        title="CORS origin 设为任意来源",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"""origin\s*:\s*['\"]\*['\"]|origin\s*:\s*true\b"""),
        message="任意网站都可以带着用户身份访问接口。",
        remediation="写成明确的 Origin 白名单。",
        cwe="CWE-942",
        suffixes=JS,
    ),
    PatternRule(
        rule_id="GO009",
        title="http.Get 没有客户端超时",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"\bhttp\.(?:Get|Post|Head|PostForm)\s*\("),
        message="默认 HTTP 客户端没有超时。",
        remediation="使用设置了 Timeout 的 http.Client。",
        cwe="CWE-400",
        suffixes=GO,
    ),
    PatternRule(
        rule_id="GO010",
        title="一次性读完未知长度的响应",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"\b(?:ioutil|io)\.ReadAll\s*\("),
        message="ReadAll 会把整个流读进内存。",
        remediation="用 LimitReader 限制大小，或流式处理。",
        cwe="CWE-400",
        suffixes=GO,
    ),
    PatternRule(
        rule_id="JV010",
        title="XMLDecoder 反序列化",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re("XML" r"Decoder\s*\("),
        message="XMLDecoder 会按 XML 构造对象。",
        remediation="对外数据使用 JSON 或明确的数据格式。",
        cwe="CWE-502",
        suffixes=JAVA,
    ),
    PatternRule(
        rule_id="JV011",
        title="使用全零 IV",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"new\s+IvParameterSpec\s*\(\s*new\s+byte\s*\["),
        message="全零或未指定内容的 IV 会让相同明文得到相同密文。",
        remediation="每次加密使用随机 IV，并和密文一起保存。",
        cwe="CWE-327",
        suffixes=JAVA,
    ),
    PatternRule(
        rule_id="JV012",
        title="Cookie 关闭 Secure",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"\.setSecure\s*\(\s*false\s*\)"),
        message="未标记 Secure 的 Cookie 可能经明文 HTTP 发出。",
        remediation="生产环境 setSecure(true)，并只走 HTTPS。",
        cwe="CWE-614",
        suffixes=JAVA,
    ),
    PatternRule(
        rule_id="PHP010",
        title="用 MD5/SHA1 处理请求字段",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"\b(?:md5|sha1)\s*\(\s*\$_(?:POST|GET|REQUEST|COOKIE)"),
        message="MD5/SHA1 不适合作为口令哈希。",
        remediation="口令使用 password_hash，不要用 md5/sha1。",
        cwe="CWE-328",
        suffixes=PHP,
    ),
    PatternRule(
        rule_id="PHP011",
        title="create_function",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re("create_" r"function\s*\("),
        message="create_function 会把字符串当代码，且已移除。",
        remediation="改用普通函数或闭包。",
        cwe="CWE-95",
        suffixes=PHP,
    ),
    PatternRule(
        rule_id="PHP012",
        title="用请求参数当远程地址读取",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\bfile_get_contents\s*\(\s*\$_"),
        message="把请求参数直接交给 file_get_contents，可能读取本地文件或任意 URL。",
        remediation="只允许固定协议和主机白名单。",
        cwe="CWE-918",
        suffixes=PHP,
    ),
    PatternRule(
        rule_id="CS007",
        title="Json.NET 允许类型名",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re("Type" r"NameHandling\.(?:All|Auto|Objects|Arrays)"),
        message="允许类型名时，JSON 可以指定要构造的类型。",
        remediation="TypeNameHandling 保持 None。",
        cwe="CWE-502",
        suffixes=CS,
    ),
    PatternRule(
        rule_id="RB006",
        title="按字符串 constantize",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\.constantize\b"),
        message="把外部字符串变成常量名，可能加载非预期的类。",
        remediation="用白名单映射字符串到类。",
        cwe="CWE-470",
        suffixes=RUBY,
    ),
    PatternRule(
        rule_id="RS006",
        title="Rust TLS 接受无效证书",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"danger_accept_invalid_certs\s*\(\s*true\s*\)"),
        message="接受无效证书会让中间人替换无法被发现。",
        remediation="保持证书校验，或只信任指定的 CA。",
        cwe="CWE-295",
        suffixes=RUST,
    ),
    PatternRule(
        rule_id="SQL007",
        title="LOAD DATA INFILE",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\bLOAD\s+DATA\s+INFILE\b"),
        message="语句会让数据库去读服务器上的文件。",
        remediation="在应用侧导入数据，并取消数据库账号的 FILE 权限。",
        cwe="CWE-73",
        suffixes=SQL,
    ),
    PatternRule(
        rule_id="SQL008",
        title="启用 xp_cmdshell",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re("xp_" r"cmdshell"),
        message="xp_cmdshell 让数据库去执行操作系统命令。",
        remediation="保持关闭；需要批处理时放到数据库之外。",
        cwe="CWE-78",
        suffixes=SQL,
    ),
    PatternRule(
        rule_id="SQL009",
        title="SELECT INTO OUTFILE",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\bINTO\s+OUTFILE\b"),
        message="查询结果被写到数据库服务器的文件里。",
        remediation="在应用侧导出，并限制数据库账号的 FILE 权限。",
        cwe="CWE-73",
        suffixes=SQL,
    ),
    PatternRule(
        rule_id="C008",
        title="使用 tmpnam / mktemp",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"\b(?:tmpnam|mktemp)\s*\("),
        message="这些函数只生成名字，创建前存在竞争窗口。",
        remediation="改用 mkstemp。",
        cwe="CWE-377",
        suffixes=C_FAM,
    ),
    PatternRule(
        rule_id="DK006",
        title="镜像构建里把下载交给 shell",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"(?:curl|wget)[^\n]*\|\s*(?:sudo\s+)?(?:ba)?sh"),
        message="构建阶段把远程脚本直接交给 shell。",
        remediation="先下载到文件，校验校验和后再执行。",
        cwe="CWE-494",
        names=frozenset({"Dockerfile", "Containerfile"}),
    ),
    PatternRule(
        rule_id="K8S006",
        title="容器根文件系统可写",
        severity=Severity.MEDIUM,
        category=Category.CONFIG,
        pattern=_re(r"readOnlyRootFilesystem\s*:\s*false"),
        message="可写的根文件系统让进程更容易落盘和持久化。",
        remediation="设为 true，只把需要写的目录挂成卷。",
        cwe="CWE-732",
        suffixes=YAML,
    ),
    PatternRule(
        rule_id="TF003",
        title="数据库对公网开放",
        severity=Severity.HIGH,
        category=Category.CONFIG,
        pattern=_re(r"publicly_accessible\s*=\s*true"),
        message="数据库实例可以从公网访问。",
        remediation="设为 false，只允许内网安全组访问。",
        cwe="CWE-284",
        suffixes=TF,
    ),
    PatternRule(
        rule_id="CFG008",
        title="数据库连接关闭 SSL",
        severity=Severity.HIGH,
        category=Category.CONFIG,
        pattern=_re(r"(?i)sslmode\s*=\s*disable"),
        message="连接串关掉了数据库 TLS。",
        remediation="使用 require 或 verify-full。",
        cwe="CWE-319",
        suffixes=PY | frozenset({".env", ".ini", ".properties", ".yml", ".yaml", ".toml"}),
    ),
    PatternRule(
        rule_id="SEC017",
        title="疑似 OpenAI 项目密钥",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(r"\bsk-proj-[A-Za-z0-9_\-]{20,}\b"),
        message="匹配到 OpenAI 项目密钥形态。",
        remediation="在平台撤销并轮换，只通过环境变量注入。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC018",
        title="疑似 PyPI 令牌",
        severity=Severity.CRITICAL,
        category=Category.SECRET,
        pattern=_re(r"\bpypi-[A-Za-z0-9_\-]{20,}\b"),
        message="匹配到 PyPI API 令牌形态。",
        remediation="在 PyPI 撤销该令牌，改用 CI 的短期凭据。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="WEB006",
        title="iframe 未设置 sandbox",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"<iframe\b(?![^>]*\bsandbox\b)"),
        message="没有 sandbox 的 iframe 拥有和嵌入页相近的能力。",
        remediation="加上 sandbox，只放开确实需要的权限。",
        cwe="CWE-1021",
        suffixes=HTML,
    ),
    PatternRule(
        rule_id="BUG032",
        title="用 len 判断空容器",
        severity=Severity.LOW,
        category=Category.QUALITY,
        pattern=_re(r"\blen\s*\([^)\n]+\)\s*(?:==|!=)\s*0\b"),
        message="用长度和 0 比较可读性差，也多一次计数。",
        remediation="写成 if not items: 或 if items:。",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="BUG033",
        title="空的 catch 块",
        severity=Severity.MEDIUM,
        category=Category.BUG,
        pattern=_re(r"catch\s*\([^)]*\)\s*\{\s*\}"),
        message="空 catch 会把失败吞掉。",
        remediation="记录异常或向上抛出。",
        suffixes=JAVA | CS | JS,
    ),
)
