"""Python-specific regex fallbacks (AST is preferred when parse succeeds)."""

from __future__ import annotations

from deepopen.models import Category, Severity
from deepopen.patterns.base import PatternRule, compile_re as _re

PY = frozenset({".py", ".pyw"})

PYTHON_RULES: tuple[PatternRule, ...] = (
    PatternRule(
        rule_id="PY001",
        title="eval / exec 执行动态代码",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\b(?:eval|exec)\s*\("),
        message="动态执行字符串会把不可信输入变成代码路径。",
        remediation="用显式分支、ast.literal_eval（仅字面量）或安全解析库替代。",
        cwe="CWE-95",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY002",
        title="pickle / marshal 反序列化",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\b(?:pickle|marshal|_pickle|dill|shelve)\.(?:loads|load|open)\s*\("),
        message="这些还原方式可执行对象构造，不适合处理不可信数据。",
        remediation="对外数据改用 JSON；不要还原不可信字节流。",
        cwe="CWE-502",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY003",
        title="shell=True 或 os.system",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(
            r"(?:os\.system\s*\(|os\.popen\s*\(|subprocess\.(?:Popen|call|run|check_output|check_call)\s*\([^)]*shell\s*=\s*True)"
        ),
        message="通过 shell 拼接命令时，特殊字符可能改变命令结构。",
        remediation="使用参数列表调用（shell=False），并对每个参数做白名单校验。",
        cwe="CWE-78",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY004",
        title="yaml.load 未指定安全 Loader",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\byaml\.(?:load|unsafe_load)\s*\("),
        message="未使用 SafeLoader 时可能构造任意对象。",
        remediation="改用 yaml.safe_load()。",
        cwe="CWE-502",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY005",
        title="关闭 TLS 证书校验",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\bverify\s*=\s*False\b"),
        message="关闭证书校验会让 HTTPS 连接容易被中间人替换。",
        remediation="保持校验；自签证书时指定 CA 路径，而不是关闭校验。",
        cwe="CWE-295",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY006",
        title="Flask / Django 调试模式可能开启",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"(?:app\.run\s*\([^)]*debug\s*=\s*True|DEBUG\s*=\s*True)"),
        message="生产环境开启调试会暴露交互式报错和内部路径。",
        remediation="生产配置强制 DEBUG=False；用环境变量区分环境。",
        cwe="CWE-489",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY007",
        title="弱哈希用于敏感数据",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"hashlib\.(?:md5|sha1)\s*\(|hashlib\.new\s*\(\s*['\"](?:md5|sha1)['\"]"),
        message="MD5/SHA1 不适合口令存储，也不适合新的完整性方案。",
        remediation="口令使用 Argon2 / bcrypt / scrypt；完整性使用 SHA-256 及以上。",
        cwe="CWE-328",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY008",
        title="SQL 字符串拼接",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(
            r"""(?:execute(?:many)?\s*\(\s*(?:f['\"]|['\"].*(?:SELECT|INSERT|UPDATE|DELETE).*%s)|(?:f['\"](?:SELECT|INSERT|UPDATE|DELETE).\{))"""
        ),
        message="把变量拼进 SQL 文本会破坏查询结构。",
        remediation="使用参数化查询（占位符 + 参数列表）。",
        cwe="CWE-89",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY009",
        title="Flask/Django 把字符串标为安全 HTML",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\b(?:mark_safe|Markup)\s*\("),
        message="跳过自动转义后，未消毒的 HTML 可能被当成页面结构执行。",
        remediation="优先依赖模板自动转义；必须输出 HTML 时先用维护中的 sanitizer。",
        cwe="CWE-79",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY010",
        title="硬编码 Django/Flask SECRET_KEY",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(r"""SECRET_KEY\s*=\s*['\"][^'\"]{8,}['\"]"""),
        message="框架密钥被写死在源码中。",
        remediation="从环境变量读取 SECRET_KEY；每个环境使用不同值。",
        cwe="CWE-798",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY011",
        title="JWT 关闭校验或允许 none 算法",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"jwt\.decode\s*\([^)]*(?:verify\s*=\s*False|algorithms\s*=\s*\[[^\]]*none)"),
        message="关闭 JWT 校验或允许 none 算法会让令牌失去完整性。",
        remediation="显式传入允许的签名算法列表，并保持校验开启。",
        cwe="CWE-347",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY012",
        title="使用已废弃的 tempfile.mktemp",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"\btempfile\.mktemp\s*\("),
        message="mktemp 在创建文件前就返回路径，存在时间窗口问题。",
        remediation="改用 tempfile.NamedTemporaryFile 或 mkstemp。",
        cwe="CWE-377",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY013",
        title="XML 解析可能允许外部实体",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"\b(?:lxml\.etree|xml\.sax|xml\.dom\.minidom|etree)\.(?:parse|fromstring|XML)\s*\("),
        message="部分 XML 解析器在默认配置下可能处理外部实体。",
        remediation="使用 defusedxml，或关闭外部实体与 DTD。",
        cwe="CWE-611",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY014",
        title="Flask 动态渲染模板字符串",
        severity=Severity.HIGH,
        category=Category.SECURITY,
        pattern=_re(r"\brender_template_string\s*\("),
        message="把不可信字符串当模板渲染可能执行模板表达式。",
        remediation="只用磁盘上的固定模板文件；用户内容当普通变量传入。",
        cwe="CWE-94",
        suffixes=PY,
    ),
    PatternRule(
        rule_id="PY015",
        title="CORS 允许任意来源",
        severity=Severity.MEDIUM,
        category=Category.SECURITY,
        pattern=_re(r"""CORS\s*\([^)]*(?:origins\s*=\s*['\"]?\*|supports_credentials\s*=\s*True)"""),
        message="过宽的 CORS 会让浏览器把带 cookie 的请求发给你的接口。",
        remediation="把允许的 Origin 写成明确白名单，凭据模式不要配 *。",
        cwe="CWE-942",
        suffixes=PY,
    ),
)
