"""Hardcoded credential patterns."""

from __future__ import annotations

from deepopen.models import Category, Severity
from deepopen.patterns.base import PatternRule, compile_re as _re

SECRET_RULES: tuple[PatternRule, ...] = (
    PatternRule(
        rule_id="SEC001",
        title="疑似硬编码私钥",
        severity=Severity.CRITICAL,
        category=Category.SECRET,
        pattern=_re(r"-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----"),
        message="源码中出现私钥 PEM 头，密钥一旦入库就很难真正撤回。",
        remediation="立刻轮换密钥；改用环境变量或密钥托管，并把私钥文件加入 .gitignore。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC002",
        title="疑似 AWS 访问密钥",
        severity=Severity.CRITICAL,
        category=Category.SECRET,
        pattern=_re(r"\bAKIA[0-9A-Z]{16}\b"),
        message="匹配到 AWS Access Key ID 形态的字符串。",
        remediation="在云控制台停用并轮换该密钥；改用 IAM 角色或运行时注入。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC003",
        title="疑似 GitHub 令牌",
        severity=Severity.CRITICAL,
        category=Category.SECRET,
        pattern=_re(r"\b(?:ghp|gho|ghu|ghs|ghr|github_pat)_[A-Za-z0-9_]{20,}\b"),
        message="匹配到 GitHub 个人访问令牌形态。",
        remediation="在 GitHub 立刻撤销该令牌，改用 CI secrets 或短期凭据。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC004",
        title="硬编码口令或 API Key 赋值",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(
            r"""(?i)\b(?:password|passwd|pwd|secret|api[_-]?key|access[_-]?token|auth[_-]?token)\b\s*[:=]\s*['\"][^'\"]{8,}['\"]"""
        ),
        message="疑似把口令、密钥或访问令牌直接写在源码里。",
        remediation="改为从环境变量或密钥管理服务读取；仓库中只保留占位符（如 CHANGE_ME）。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC005",
        title="疑似 Slack 令牌",
        severity=Severity.CRITICAL,
        category=Category.SECRET,
        pattern=_re(r"\bxox[baprs]-[0-9A-Za-z-]{10,}\b"),
        message="匹配到 Slack 令牌形态。",
        remediation="在 Slack 管理端撤销该令牌，改用运行时注入。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC006",
        title="疑似 Google API Key",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(r"\bAIza[0-9A-Za-z\-_]{35}\b"),
        message="匹配到 Google API Key 形态。",
        remediation="在 Google Cloud 限制密钥、轮换后改用环境变量。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC007",
        title="疑似 Stripe 密钥",
        severity=Severity.CRITICAL,
        category=Category.SECRET,
        pattern=_re(r"\bsk_live_[0-9a-zA-Z]{10,}\b"),
        message="匹配到 Stripe 生产密钥形态。",
        remediation="在 Stripe 控制台立刻轮换，改用服务端密钥托管。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC008",
        title="疑似 OpenAI 密钥",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(r"\bsk-[A-Za-z0-9]{20,}\b"),
        message="匹配到 OpenAI 密钥形态。",
        remediation="在平台撤销并轮换；只通过环境变量注入。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC009",
        title="疑似私钥赋值",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(r"""(?i)\b(?:private[_-]?key|secret[_-]?access[_-]?key)\b\s*[:=]\s*['\"][^'\"]{12,}['\"]"""),
        message="疑似把私钥或云密钥写进赋值语句。",
        remediation="改用密钥托管或环境变量，并轮换已暴露的密钥。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC010",
        title="连接串中含明文口令",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(r"(?i)(?:mysql|postgres|mongodb|redis|amqp|jdbc):[^\s'\"]*://[^\s'\"]+:[^\s'\"]+@"),
        message="连接字符串把用户名和口令写在 URL 里。",
        remediation="把口令拆到环境变量或密钥服务，连接串不要提交到仓库。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC011",
        title="疑似 JWT 被硬编码",
        severity=Severity.MEDIUM,
        category=Category.SECRET,
        pattern=_re(r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b"),
        message="出现完整 JWT 形态，可能是真实会话令牌。",
        remediation="不要把真实 JWT 写进源码或测试夹具；用 mock 或运行时获取。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC012",
        title="疑似 npm / GitHub Packages 令牌",
        severity=Severity.CRITICAL,
        category=Category.SECRET,
        pattern=_re(r"\bnpm_[A-Za-z0-9]{20,}\b"),
        message="匹配到 npm 访问令牌形态。",
        remediation="在 npm 撤销令牌，改用 CI 提供的短期凭据。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC013",
        title="疑似 Slack Webhook",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(r"hooks\.slack\.com/services/[A-Za-z0-9/_-]+"),
        message="匹配到 Slack Incoming Webhook 路径。",
        remediation="在 Slack 撤销该 webhook，改用运行时配置。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC014",
        title="疑似 GitLab 令牌",
        severity=Severity.CRITICAL,
        category=Category.SECRET,
        pattern=_re(r"\bglpat-[A-Za-z0-9_\-]{20,}\b"),
        message="匹配到 GitLab 个人访问令牌形态。",
        remediation="在 GitLab 立刻撤销该令牌，改用 CI 变量注入。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC015",
        title="疑似 Hugging Face 令牌",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(r"\bhf_[A-Za-z0-9]{20,}\b"),
        message="匹配到 Hugging Face 访问令牌形态。",
        remediation="在平台撤销并轮换，只通过环境变量注入。",
        cwe="CWE-798",
    ),
    PatternRule(
        rule_id="SEC016",
        title="疑似 Anthropic 密钥",
        severity=Severity.HIGH,
        category=Category.SECRET,
        pattern=_re(r"\bsk-ant-[A-Za-z0-9_\-]{20,}\b"),
        message="匹配到 Anthropic API 密钥形态。",
        remediation="在控制台轮换密钥，改用运行时注入。",
        cwe="CWE-798",
    ),
)